insert into `type`(`id`,`name`) values(1,'日报'),(2,'周报'),(3,'月报');
INSERT INTO `spider_junior`.`company` (`id`, `name`) VALUES ('1', '优酷');
INSERT INTO `spider_junior`.`company` (`id`, `name`) VALUES ('2', '迅雷');
INSERT INTO `spider_junior`.`company` (`id`, `name`) VALUES ('3', '百度');
INSERT INTO `spider_junior`.`company` (`id`, `name`) VALUES ('4', '奇艺');
INSERT INTO `spider_junior`.`company` (`id`, `name`) VALUES ('5', '搜狐');
INSERT INTO `spider_junior`.`company` (`id`, `name`) VALUES ('6', '乐视');
INSERT INTO `spider_junior`.`data_source` (`id`, `name`, `company_id`, `url`, `type_id`) VALUES ('1', '百度电视剧日报', '3', 'http://top.baidu.com/buzz.php?p=tv', '1');
INSERT INTO `spider_junior`.`data_source` (`id`, `name`, `company_id`, `url`, `type_id`) VALUES ('2', '百度电影日报', '3', 'http://top.baidu.com/buzz.php?p=movie', '1');
INSERT INTO `spider_junior`.`data_source` (`id`, `name`, `company_id`, `url`, `type_id`) VALUES ('3', '看看电视剧日报', '2', 'http://movie.kankan.com/top/teleplay.html', '1');
INSERT INTO `spider_junior`.`data_source` (`id`, `name`, `company_id`, `url`, `type_id`) VALUES ('4', '看看电影日报', '2', 'http://movie.kankan.com/top/movie.html', '1');
